"""empty message

Revision ID: cd0028e7aff6
Revises: 683e8d57121d
Create Date: 2023-08-16 23:45:41.798419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0028e7aff6'
down_revision = '683e8d57121d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
